// TierCard — a single tier column in the 4-tier pricing grid.
//
// Renders one of Free / Hobby / Pro / Team with:
//   - Most Popular badge (Pro only, driven by `highlight` prop so this
//     component never hardcodes a tier-name guard — the parent decides).
//   - Raised + thick-border treatment when `highlight` is true so Pro
//     visually anchors the grid (research: middle-tier badge + raised
//     treatment lifts conversion 25–158% — see PRICING-BEST-PRACTICES).
//   - "Your plan" pill in place of the CTA on the user's current tier.
//   - Frequency-aware price + subtext: when annual, shows the headline
//     monthly-equivalent ($7.50/mo) with the yearly total + savings
//     subtext ($90/yr · save $18). When monthly, shows the bare monthly
//     price ($9/mo).
//   - Tier-aware CTA copy: "Get Pro — $7.50/mo" (annual) /
//     "Get Pro — $9/mo" (monthly), generated by the parent's
//     `buildCtaLabel`.
//
// Pure presentational + click-through — checkout side-effects live on
// the parent (BillingPage / PricingGrid). Tests can render this card in
// isolation by passing the props directly.

import type { ReactNode } from 'react'

// TierKey — every grid tier the dashboard renders. W11 added `hobby_plus`
// as the $19/mo mid-step between Hobby ($9) and Pro ($49); see
// PricingGrid.tsx for the per-tier feature list.
export type TierKey = 'free' | 'hobby' | 'hobby_plus' | 'pro' | 'team'
export type Frequency = 'monthly' | 'yearly'

export interface TierPricing {
  // Headline price string ("$9", "$7.50", "Free", etc.) — already formatted
  // for the active frequency. Keep dollar sign on the parent side so
  // currency swaps stay in one place.
  headline: string
  // Subtext below the headline ("/mo", "/mo, billed yearly", "forever").
  subtext: string
  // Optional savings line ("$90/yr · save $18"). Rendered when set;
  // skipped on tiers without a yearly variant (Free).
  savings?: string
}

export interface TierCardProps {
  tier: TierKey
  label: string
  pricing: TierPricing
  features: Array<{ text: string; comingSoon?: boolean }>
  highlight?: boolean
  isCurrent?: boolean
  // CTA: rendered when `ctaLabel` is non-empty. `onCta` runs the action.
  // Falsy `ctaLabel` => no CTA (Free + Team without an upgrade target).
  ctaLabel?: string
  onCta?: () => void
  ctaDisabled?: boolean
  ctaTestId?: string
  ctaSlot?: ReactNode  // optional override (e.g. UpgradeButton with A/B variant)
  // Test hook
  testId?: string
}

export function TierCard({
  tier,
  label,
  pricing,
  features,
  highlight = false,
  isCurrent = false,
  ctaLabel,
  onCta,
  ctaDisabled,
  ctaTestId,
  ctaSlot,
  testId,
}: TierCardProps) {
  const dataTestId = testId ?? `tier-card-${tier}`
  return (
    <article
      data-testid={dataTestId}
      data-tier={tier}
      data-highlight={highlight ? 'true' : 'false'}
      data-current={isCurrent ? 'true' : 'false'}
      style={{
        position: 'relative',
        display: 'flex',
        flexDirection: 'column',
        gap: 10,
        padding: highlight ? '24px 18px 18px' : '20px 16px 16px',
        background: highlight ? 'var(--elevated, var(--surface))' : 'var(--surface)',
        border: highlight ? '1px solid var(--accent)' : '1px solid var(--border)',
        // Thicker visual emphasis on the highlighted tier: doubled
        // box-shadow ring + slight inset to lift it off the page.
        boxShadow: highlight
          ? '0 0 0 1px var(--accent), 0 8px 24px -10px rgba(0,228,142,0.25)'
          : 'none',
        borderRadius: 10,
        minWidth: 0,
      }}
    >
      {highlight && (
        <span
          data-testid="tier-most-popular-badge"
          aria-label="Most popular plan"
          style={{
            position: 'absolute',
            top: -10,
            left: 14,
            padding: '2px 8px',
            fontFamily: 'var(--font-mono)',
            fontSize: 10.5,
            fontWeight: 600,
            letterSpacing: '0.08em',
            textTransform: 'uppercase',
            color: 'var(--ink)',
            background: 'var(--accent)',
            border: '1px solid var(--accent)',
            borderRadius: 4,
          }}
        >
          Most Popular
        </span>
      )}
      <div
        style={{
          fontFamily: 'var(--font-mono)',
          fontSize: 10.5,
          color: tier === 'team' ? 'var(--text-faint)' : 'var(--text-dim)',
          textTransform: 'uppercase',
          letterSpacing: '0.06em',
        }}
      >
        {label}
      </div>
      <div
        data-testid={`tier-price-${tier}`}
        style={{ display: 'flex', alignItems: 'baseline', gap: 6 }}
      >
        <span
          style={{
            fontFamily: 'var(--font-display, inherit)',
            fontSize: highlight ? 30 : 26,
            fontWeight: 400,
            letterSpacing: '-0.03em',
            // Team is the anchor — de-emphasised price.
            color: tier === 'team' ? 'var(--text-dim)' : 'var(--text)',
          }}
        >
          {pricing.headline}
        </span>
        <span
          style={{
            fontFamily: 'var(--font-mono)',
            fontSize: 11.5,
            color: 'var(--text-dim)',
          }}
        >
          {pricing.subtext}
        </span>
      </div>
      {pricing.savings && (
        <div
          data-testid={`tier-savings-${tier}`}
          style={{
            fontFamily: 'var(--font-mono)',
            fontSize: 11,
            color: 'var(--text-faint)',
            letterSpacing: '0.03em',
          }}
        >
          {pricing.savings}
        </div>
      )}
      <ul
        style={{
          listStyle: 'none',
          padding: 0,
          margin: '4px 0 8px',
          display: 'flex',
          flexDirection: 'column',
          gap: 5,
          flex: '1 1 auto',
        }}
      >
        {features.map((f, i) => (
          <li
            key={i}
            style={{
              fontSize: 12.5,
              lineHeight: 1.5,
              color: 'var(--text-dim)',
              opacity: f.comingSoon ? 0.6 : 1,
            }}
          >
            {f.text}
            {f.comingSoon && (
              <span
                style={{
                  marginLeft: 6,
                  padding: '1px 6px',
                  fontSize: 10,
                  fontFamily: 'var(--font-mono)',
                  color: 'var(--violet)',
                  border: '1px solid rgba(183,148,246,0.3)',
                  borderRadius: 4,
                  textTransform: 'uppercase',
                  letterSpacing: 0.06,
                }}
              >
                soon
              </span>
            )}
          </li>
        ))}
      </ul>
      {isCurrent ? (
        <span
          data-testid={`tier-your-plan-${tier}`}
          aria-label={`${label} is your current plan`}
          style={{
            alignSelf: 'flex-start',
            padding: '6px 12px',
            fontFamily: 'var(--font-mono)',
            fontSize: 11,
            fontWeight: 500,
            color: 'var(--text-dim)',
            background: 'transparent',
            border: '1px solid var(--border-hi, var(--border))',
            borderRadius: 4,
            textTransform: 'uppercase',
            letterSpacing: '0.06em',
          }}
        >
          Your plan
        </span>
      ) : ctaSlot ? (
        // Pro's CTA composes with UpgradeButton (P1 A/B variant). The
        // parent passes the prebuilt button element. We never wrap or
        // restyle it here — UpgradeButton owns its own styling so the
        // experiment variants stay visually consistent.
        ctaSlot
      ) : ctaLabel ? (
        <button
          type="button"
          className="btn btn-secondary btn-sm"
          onClick={onCta}
          disabled={ctaDisabled || !onCta}
          data-testid={ctaTestId ?? `tier-cta-${tier}`}
          style={{ alignSelf: 'flex-start' }}
        >
          {ctaLabel}
        </button>
      ) : null}
    </article>
  )
}
